# configs/config.yaml

data:
  train_csv: "data_v2/metadata/train.csv"
  val_csv: "data_v2/metadata/val.csv"
  test_csv: "data_v2/metadata/test.csv"

  img_size: 224
  batch_size: 16
  num_workers: 2

save_dir: "/content/drive/MyDrive/pneumonia-vit-v2/output"
# save_dir: "/outputs"

model:
  name: "vit_base_patch16_224"
  num_classes: 8
  pretrained: true

  v1_checkpoint: "best_model.pth"

train:
  epochs: 15
  lr: 0.00001
  weight_decay: 0.01
  lr: 0.00001
device: "cuda"
